### ISSUE TITLE
查询历史不能工作

### ISSUE THREAD

**Issue by ahjsrhj** [roylez/alfred_kuaidi#3]
报错如下:

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: ./list_query.rb:62:in `strip': invalid byte sequence in US-ASCII (ArgumentError)
    from ./list_query.rb:62:in `possible_clipboard_tracking_number'
    from ./list_query.rb:72:in `<main>'
```

Google之后在list_query.rb文件头部加上`# encoding: utf-8`，解决。

**Comment by roylez** [comment]
谢谢，已经修复 100fc7e
